#!/bin/sh
#===============================================================================
#
#
#  Copyright (C) 2025 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#
#  !Description: DRM APIs Library
#
#===============================================================================